<?php
return [
	'location_head_low'					=> 'Baixo',
	'location_right_hand'				=> 'Mão Direita',
	'location_garment'					=> 'Capa',
	'location_right_accessory'			=> 'Accessório Direito',
	'location_armor'					=> 'Armadura',
	'location_left_hand'				=> 'Mão Esquerda',
	'location_shoes'					=> 'Sapatos',
	'location_left_accessory'			=> 'Accessório Esquerdo',
	'location_head_top'					=> 'Topo',
	'location_head_mid'					=> 'Meio',
	'location_costume_head_top'			=> 'Custom Topo',
	'location_costume_head_mid'			=> 'Custom Meio',
	'location_costume_head_low'			=> 'Custom Baixo',
	'location_costume_garment'			=> 'Custom Capa',
	'location_ammo'						=> 'Munição',
	'location_shadow_armor'				=> 'Sombra de Armadura',
	'location_shadow_weapon'			=> 'Sombra de Arma',
	'location_shadow_shield'			=> 'Sombra de Escudo',
	'location_shadow_shoes'				=> 'Sombra de Sapato',
	'location_shadow_right_accessory'	=> 'Sombra de Accessório Direito (Brinco)',
	'location_shadow_left_accessory'	=> 'Sombra de Accessório Esquerdo (Pingente)',
]
?>
