<?php
return [
	'01' => ['mode_canattack', 'mode_canmove'],
	'02' => ['mode_canattack', 'mode_looter', 'mode_canmove'],
	'03' => ['mode_changetargetmelee', 'mode_canattack', 'mode_assist', 'mode_canmove'],
	'04' => ['mode_changetargetchase', 'mode_changetargetmelee', 'mode_angry', 'mode_canattack', 'mode_aggressive', 'mode_canmove'],
	'05' => ['mode_changetargetchase', 'mode_canattack', 'mode_aggressive', 'mode_canmove'],
	'06' => [],
	'07' => ['mode_changetargetmelee', 'mode_canattack', 'mode_assist', 'mode_looter', 'mode_canmove'],
	'08' => ['mode_targetweak', 'mode_changetargetchase', 'mode_changetargetmelee', 'mode_canattack', 'mode_aggressive', 'mode_canmove'],
	'09' => ['mode_changetargetchase', 'mode_changetargetmelee', 'mode_canattack', 'mode_castsensoridle', 'mode_aggressive', 'mode_canmove'],
	'10' => ['mode_canattack', 'mode_aggressive'],
	'11' => ['mode_canattack', 'mode_aggressive'],
	'12' => ['mode_changetargetchase', 'mode_canattack', 'mode_aggressive', 'mode_canmove'],
	'13' => ['mode_changetargetchase', 'mode_changetargetmelee', 'mode_canattack', 'mode_assist', 'mode_aggressive', 'mode_canmove'],
	//14 => [],
	//15 => [],
	//16 => [],
	'17' => ['mode_canattack', 'mode_castsensoridle', 'mode_canmove'],
	//18 => [],
	'19' => ['mode_changetargetchase', 'mode_changetargetmelee', 'mode_canattack', 'mode_castsensoridle', 'mode_aggressive', 'mode_canmove'],
	'20' => ['mode_changetargetchase', 'mode_changetargetmelee', 'mode_castsensorchase', 'mode_canattack', 'mode_castsensoridle', 'mode_aggressive', 'mode_canmove'],
	'21' => ['mode_changetargetchase', 'mode_changetargetmelee', 'mode_changechase', 'mode_castsensorchase', 'mode_canattack', 'mode_castsensoridle', 'mode_aggressive', 'mode_canmove'],
	//22 => [],
	//23 => [],
	'24' => ['mode_canattack', 'mode_norandomwalk', 'mode_canmove'],
	'25' => ['mode_canmove'],
	'26' => ['mode_randomtarget', 'mode_changetargetchase', 'mode_changetargetmelee', 'mode_changechase', 'mode_castsensorchase', 'mode_canattack', 'mode_castsensoridle', 'mode_aggressive', 'mode_canmove'],
	'27' => ['mode_randomtarget', 'mode_canattack', 'mode_aggressive'],
];
?>
