<?php
return [
	'mode_aggressive' => 'Agressivo',
	'mode_angry' => 'Irritado',
	'mode_assist' => 'Assistir',
	'mode_canattack' => 'Pode Atacar',
	'mode_canmove' => 'Pode Mover',
	'mode_castsensorchase' => 'Sensor de Lançamento de Perseguição',
	'mode_castsensoridle' => 'Sensor de Lançamento de Inatividade',
	'mode_changechase' => 'Mudar Perseguição',
	'mode_changetargetchase' => 'Mudar Alvo de Perseguição',
	'mode_changetargetmelee' => 'Mudar Alvo de Combate Corpo a Corpo',
	'mode_detector' => 'Detector',
	'mode_fixeditemdrop' => 'Drop de Item Fixo',
	'mode_ignoremagic' => 'Ignorar Magia',
	'mode_ignoremelee' => 'Ignorar Ataques Corpo a Corpo',
	'mode_ignoremisc' => 'Ignorar Diversos',
	'mode_ignoreranged' => 'Ignorar Ataques à Distância',
	'mode_knockbackimmune' => 'Imune a Empurrões',
	'mode_looter' => 'Catador',
	'mode_mvp' => 'MVP',
	'mode_norandomwalk' => 'Imóvel',
	'mode_randomtarget' => 'Alvo Aleatório',
	'mode_skillimmune' => 'Imune a Habilidades',
	'mode_statusimmune' => 'Imune a Estados',
	'mode_targetweak' => 'Alvo Fraco',
	'mode_teleportblock' => 'Bloqueio de Teleporte',
];
?>
