<?php
return [
	'A' => 'Admin',
	'B' => 'Comprado na Loja',
	'C' => 'Consumido',
	'D' => 'Roubado/Assaltado',
	'E' => 'Enviado por Correio',
	'F' => 'Recuperação de Item Vinculado',
	'G' => 'Armazenamento de Guilda',
	//'H' => '',
	'I' => 'Leiloado',
	//'J' => '',
	'K' => 'Banco',
	'L' => 'Saqueado',
	'M' => 'Monstro',
	'N' => 'NPC (Script)',
	'O' => 'Produzido',
	'P' => 'Jogador',
	'Q' => 'Missão',
	'R' => 'Armazenamento',
	'S' => 'NPC (Loja)',
	'T' => 'Negociado',
	'U' => 'MVP',
	'V' => 'Vendido',
	//'W' => '',
	'X' => 'Outro',
	'Y' => 'Loteria',
	'Z' => 'Mesclado',
	'$' => 'Dinheiro',
];
?>
